# -*- coding: utf-8 -*-
"""ML-Reg-Mulitple-Linear-Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nhkO-Op98Z3QqJmDpB8cS-NQdduU1A1M
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Read the dataset
df = pd.read_csv("/content/study_performance.csv")

# Train/test split
train, test = train_test_split(df, test_size=0.2, random_state=42)

# Linear Regression model
regr = LinearRegression()

# Features and target
X_train = train[['parental_level_of_education', 'math_score', 'reading_score']]
y_train = train['writing_score']

X_test = test[['parental_level_of_education', 'math_score', 'reading_score']]
y_test = test['writing_score']

# One-hot encoding for 'parental_level_of_education'
X_train = pd.get_dummies(X_train, columns=['parental_level_of_education'])
X_test = pd.get_dummies(X_test, columns=['parental_level_of_education'])

# Train the model
regr.fit(X_train, y_train)

# Make predictions
y_pred = regr.predict(X_test)

# Evaluation
print('Coefficients:', regr.coef_)
print('Mean Squared Error (MSE): %.2f' % mean_squared_error(y_test, y_pred))
print('Variance score: %.2f' % r2_score(y_test, y_pred))